### PR TITLE
fix windows bug

### PR DESCRIPTION
**Pull request by adam-martin**
HOMEPATH w/o drive letter vs USERPROFILE
...
Error: ENOENT, no such file or directory 'X:\Users\Adam\.netrc'
HOMEPATH = \Users\Adam\ but HOMEDRIVE = C:

### CODE REVIEW

**Comment by kennethormandy** [comment]
Hey, thanks so much for the pull request! I believe this is the first one from outside our team.

I’ve been testing Surge on Windows and I can’t seem to recreate the initial issue that this is trying to solve. Would you mind providing some more details for me? How to reproduce it if you know?

I do think this might be the same issue @davidwesst [encountered](https://twitter.com/davidwesst/status/573329383261261824) if he doesn’t mind chiming in too. :phone:

**Comment by davidwesst** [comment]
So someone else hit the same thing eh? Cool. I'll take some time today to try and reproduce the bug and log it on here for reference, and I'll try the fixed code as well.

**Comment by kennethormandy** [comment]
Thanks so much David! Anything you can do to point us in the right direction would be incredibly helpful.

**Comment by davidwesst** [comment]
I managed to reproduce the bug on my end and document the steps. The assumptions about my environment are:
* Windows 8.1
* Windows, NodeJS/NPM installed on C:
* Code being published is on different logical partition (i.e. E:)

## Problem
It appears to check the partition that the code is saved onto. So, the error is thrown if I run it on the C drive, but when I try and run in when I'm on the E drive, it throws the error as it can't find the user directory.

## Steps
1. Install surge 0.8.1 globally
2. Open command line and navigate to different partition
2. Run surge from code directory on different partition (e.g. E:\Code\davidwesst-surge)
3. Enter email
4. Enter password
5. DONE -- Error is thrown

## Error Message / Stack Trace
Error: ENOENT, no such file or directory 'E:\Users\David\.netrc'
    at Object.fs.openSync (fs.js:438:18)
    at Object.fs.writeFileSync (fs.js:977:15)
    at Object.set (C:\Dev\nodejs\node_modules\surge\lib\middleware\util\creds.js:47:10)
    at Request._callback (C:\Dev\nodejs\node_modules\surge\lib\middleware\util\helpers.js:78:40)
    at Request.self.callback (C:\Dev\nodejs\node_modules\surge\node_modules\request\request.js:123:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (C:\Dev\nodejs\node_modules\surge\node_modules\request\request.js:1047:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Dev\nodejs\node_modules\surge\node_modules\request\request.js:998:12)
    at IncomingMessage.emit (events.js:117:20)

**Comment by davidwesst** [comment]
Another thing: I tried replacing my copy of surge with those from @adam-martin and following the same steps I get a different error (see below). Not sure if I followed proper testing procedures (just replaced the first in \nodejs\node_modules\surge\lib with the ones downloaded straight from GitHub.

Either way, appears to be looking in a directory that existing, which is a step in the right direction.

## Error / Stack Trace
TypeError: Cannot read property 'email' of null
    at C:\Dev\nodejs\node_modules\surge\lib\middleware\auth.js:39:62
    at Request._callback (C:\Dev\nodejs\node_modules\surge\lib\middleware\util\helpers.js:79:9)
    at Request.self.callback (C:\Dev\nodejs\node_modules\surge\node_modules\request\request.js:123:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (C:\Dev\nodejs\node_modules\surge\node_modules\request\request.js:1047:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Dev\nodejs\node_modules\surge\node_modules\request\request.js:998:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)

**Comment by adam-martin** [comment]
netrc - module dependency has same error - https://github.com/CamShaft/netrc.git
fix in index.js:15
  var home = process.env[(/^win/.test(process.platform)) ? 'USERPROFILE' : 'HOME'];//process.env.HOME || process.env.HOMEPATH;

**Comment by sintaxi** [comment]
Thank you so much! Testing on windows is a challenge. This is very much appreciated.

**Pull request merged**
